version: '3'
services:
  api:
    build: .
    depends_on:
        - postgres
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    environment:
            - DATABASE_HOSTNAME = postgres
            - DATABASE_PORT = 5432
            - DATABASE_PASSWORD = assasin1q2w
            - DATABASE_NAME = fastapi
            - DATABASE_USERNAME = postgres 

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=assasin1q2w
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes: 
  postgres-db:
           

