version: '3'
services:
  api:
    image: kost9/fastapi
    depends_on:
        - postgres
    ports: 
      - 80:8000
    # env_file:
    #     - ./.env
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    environment:
      - DATABASE_HOSTNAME = ${DATABASE_HOSTNAME}
      - DATABASE_PORT = ${DATABASE_PORT}
      - DATABASE_PASSWORD = ${DATABASE_PASSWORD}
      - DATABASE_NAME = ${DATABASE_NAME}
      - DATABASE_USERNAME = ${DATABASE_USERNAME}

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes: 
  postgres-db:
           

