name: Build and Deploy code 

on:
  push:
    branches: ["main"] #kik

jobs: 
  job1:
      runs-on: ubuntu-latest
      steps: 
        - name: pulling git repo
        - uses: actions/checkout@v2
        